import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 48,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.5,
  },
  title: {
    fontSize: 20,
    marginBottom: 8,
    fontFamily: "Helvetica-Bold",
  },
  meta: {
    fontSize: 10,
    color: "#444",
    marginBottom: 24,
  },
  sectionLabel: {
    fontSize: 10,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    textTransform: "uppercase",
    color: "#666",
  },
  body: {
    fontSize: 11,
    whiteSpace: "pre-wrap",
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    fontSize: 9,
    color: "#888",
    textAlign: "center",
  },
});

interface PolicyPdfDocumentProps {
  title: string;
  description?: string | null;
  status: string;
  version: number;
  approvedAt?: Date | null;
  authorName: string;
  content: string;
  attachmentNote?: string | null;
}

export function PolicyPdfDocument({
  title,
  description,
  status,
  version,
  approvedAt,
  authorName,
  content,
  attachmentNote,
}: PolicyPdfDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <View style={styles.meta}>
          {description ? <Text>{description}</Text> : null}
          <Text>
            Version {version} · {status}
            {approvedAt
              ? ` · Approved ${approvedAt.toLocaleDateString()}`
              : ""}
          </Text>
          <Text>Author: {authorName}</Text>
        </View>
        <Text style={styles.sectionLabel}>Policy content</Text>
        <Text style={styles.body}>{content}</Text>
        {attachmentNote ? (
          <View style={{ marginTop: 16 }}>
            <Text style={styles.sectionLabel}>Attachment</Text>
            <Text style={styles.body}>{attachmentNote}</Text>
          </View>
        ) : null}
        <Text style={styles.footer}>Generated by FINDEN ISMS</Text>
      </Page>
    </Document>
  );
}
