import ExcelJS from "exceljs";

import { prisma } from "@/lib/database/client";
import {
  buildMonthlySirBlankTemplate,
  parseMonthlySirUpload,
} from "@/features/monthly-sir/services/monthly-sir.workbook";

jest.mock("@/lib/database/client", () => ({
  prisma: {
    stockCountSession: { findFirst: jest.fn() },
  },
}));

describe("P-Count blank template and upload parser", () => {
  it("downloads only Branch, Serial Number, and P-Count with no data rows", async () => {
    (prisma.stockCountSession.findFirst as jest.Mock).mockResolvedValue({
      branch: { sapCode: "BR01" },
    });

    const { buffer } = await buildMonthlySirBlankTemplate({
      tenantId: "tenant-1",
      sessionId: "session-1",
    });
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer as unknown as ArrayBuffer);
    const sheet = workbook.worksheets[0];
    expect(sheet).toBeDefined();
    const header = ["BRANCH", "SERIAL NUMBER", "P-COUNT"];
    header.forEach((label, index) => {
      expect(sheet!.getRow(1).getCell(index + 1).value).toBe(label);
    });
    expect(sheet!.getRow(2).getCell(1).value).toBeNull();
    expect(sheet!.columnCount).toBe(3);
  });

  it("parses the blank template once the user fills P-Count", async () => {
    (prisma.stockCountSession.findFirst as jest.Mock).mockResolvedValue({
      branch: { sapCode: "BR01" },
    });
    const { buffer } = await buildMonthlySirBlankTemplate({
      tenantId: "tenant-1",
      sessionId: "session-1",
    });
    const workbook = new ExcelJS.Workbook();
    await workbook.xlsx.load(buffer as unknown as ArrayBuffer);
    workbook.worksheets[0]!.addRow(["Main", "SN-NEW", "DU"]);
    const filled = Buffer.from(await workbook.xlsx.writeBuffer());

    await expect(parseMonthlySirUpload(filled)).resolves.toEqual([
      { rowNumber: 2, serialNo: "SN-NEW", pcount: "DU" },
    ]);
  });

  it("still reads the older sheet whose headers sit on row 5", async () => {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet("P-COUNT");
    sheet.addRow(["P-COUNT - ( Branch )"]);
    sheet.addRow(["DATETIME GENERATED"]);
    sheet.addRow(["GENERATED BY"]);
    sheet.addRow([]);
    sheet.addRow(["BRANCH", "SERIAL NUMBER", "P-COUNT"]);
    sheet.addRow(["Main", "SN-1", "STK"]);
    const buffer = Buffer.from(await workbook.xlsx.writeBuffer());

    await expect(parseMonthlySirUpload(buffer)).resolves.toEqual([
      { rowNumber: 6, serialNo: "SN-1", pcount: "STK" },
    ]);
  });
});
