/** Shared seed constants — no DB access. */

export const DEMO_PASSWORD = "DemoPass123";

/** Reserved platform home tenant for Provider Dashboard operators. */
export const PLATFORM_TENANT = {
  slug: "pixelcare",
  name: "Pixelcare Consulting",
  tagline: "ISMS platform operator",
} as const;

export const PLATFORM_PROVIDER_USER = {
  email: "provider@pixelcareconsulting.com",
  name: "Pixelcare Provider",
  roleSlug: "super_admin",
} as const;

export const DEMO_USERS = [
  { email: "superadmin@demo.local", name: "Super Admin", roleSlug: "super_admin" },
  { email: "admin@demo.local", name: "Tenant Admin", roleSlug: "tenant_admin" },
  { email: "isms@demo.local", name: "ISMS Manager", roleSlug: "isms_manager" },
  { email: "auditor@demo.local", name: "Auditor", roleSlug: "auditor" },
  { email: "depthead@demo.local", name: "Department Head", roleSlug: "dept_head" },
  { email: "employee@demo.local", name: "Employee", roleSlug: "employee" },
  { email: "ps@demo.local", name: "Branch PS", roleSlug: "ps" },
  { email: "tl@demo.local", name: "Team Leader", roleSlug: "tl" },
  { email: "sp@demo.local", name: "Sales Planner", roleSlug: "sp" },
  { email: "spa@demo.local", name: "Supply Planning Associate", roleSlug: "spa" },
  { email: "logistics@demo.local", name: "Logistics", roleSlug: "logistics" },
  { email: "ae@demo.local", name: "Area Executive", roleSlug: "ae" },
  { email: "accounting@demo.local", name: "Accounting", roleSlug: "accounting" },
] as const;

export const PERMISSIONS = [
  { slug: "dashboard.manage", name: "Manage Dashboard" },
  { slug: "company.view", name: "View company settings" },
  { slug: "company.manage", name: "Manage company settings" },
  { slug: "users.view", name: "View users" },
  { slug: "users.manage", name: "Manage users" },
  { slug: "departments.view", name: "View departments" },
  { slug: "departments.manage", name: "Manage departments" },
  { slug: "roles.manage", name: "Manage roles" },
  { slug: "policies.view", name: "View policies" },
  { slug: "policies.create", name: "Create policies" },
  { slug: "policies.approve", name: "Approve policies" },
  { slug: "audits.create", name: "Create audits" },
  { slug: "audits.close", name: "Close audits" },
  { slug: "reports.view", name: "View reports" },
  { slug: "reports.export", name: "Export reports" },
  { slug: "audit_logs.view", name: "View system logs" },
  { slug: "serial_logs.view", name: "View serial number logs" },
  { slug: "branches.view", name: "View branches" },
  { slug: "branches.manage", name: "Manage branches" },
  { slug: "dealers.view", name: "View dealers" },
  { slug: "dealers.manage", name: "Manage dealers" },
  { slug: "service_centers.view", name: "View service centers" },
  { slug: "service_centers.manage", name: "Manage service centers" },
  { slug: "service_centers.inventory.view", name: "View service center inventory" },
  { slug: "service_centers.sales.view", name: "View service center sales" },
  { slug: "service_centers.sales.create", name: "Create service center sales" },
  { slug: "service_centers.return.request", name: "Request service center return (ATR)" },
  { slug: "service_centers.return.evaluate", name: "Evaluate service center return (CS)" },
  { slug: "service_centers.return.approve", name: "Approve service center return (TL)" },
  { slug: "service_centers.return.complete", name: "Complete service center return / restore stock" },
  { slug: "service_centers.orders.view", name: "View service center orders" },
  { slug: "service_centers.orders.create", name: "Create service center orders" },
  { slug: "service_centers.orders.approve", name: "Approve service center orders" },
  { slug: "service_centers.logistics.view", name: "View service center logistics" },
  { slug: "service_centers.logistics.create", name: "Create service center logistics" },
  { slug: "service_centers.logistics.manage", name: "Manage service center logistics" },
  { slug: "warehouses.view", name: "View warehouses" },
  { slug: "warehouses.manage", name: "Manage warehouses" },
  { slug: "master_data.view", name: "View master data" },
  { slug: "master_data.manage", name: "Manage master data" },
  { slug: "status_settings.view", name: "View status settings" },
  { slug: "status_settings.manage", name: "Manage status settings" },
  { slug: "ordering_settings.view", name: "View ordering policy" },
  { slug: "ordering_settings.manage", name: "Manage ordering policy" },
  { slug: "aors.view", name: "View areas of responsibility" },
  { slug: "aors.manage", name: "Manage areas of responsibility" },
  { slug: "inventory.view", name: "View inventory" },
  { slug: "inventory.manage", name: "Manage inventory" },
  { slug: "orders.view", name: "View branch orders" },
  { slug: "orders.create", name: "Create branch orders" },
  { slug: "orders.approve", name: "Approve branch orders" },
  { slug: "orders.manual.view", name: "View manual orders" },
  { slug: "orders.manual.create", name: "Create manual orders" },
  { slug: "orders.manual.approve", name: "Approve manual orders" },
  { slug: "orders.special.view", name: "View special orders" },
  { slug: "orders.special.create", name: "Create special orders" },
  { slug: "orders.special.approve", name: "Approve special orders" },
  { slug: "orders.auto_replenish.view", name: "View auto-replenish orders" },
  { slug: "orders.auto_replenish.create", name: "Create auto-replenish orders" },
  { slug: "orders.auto_replenish.approve", name: "Approve auto-replenish orders" },
  { slug: "logistics.view", name: "View logistics" },
  { slug: "logistics.create", name: "Create logistics transactions" },
  { slug: "logistics.manage", name: "Manage logistics" },
  { slug: "sap.view", name: "View SAP integration" },
  { slug: "sap.manage", name: "Manage SAP integration" },
  { slug: "sales.view", name: "View sales and ATR" },
  { slug: "sales.create", name: "Create sales transactions" },
  { slug: "sales.update", name: "Edit sales transaction headers" },
  { slug: "sales.return.view", name: "View sales returns (ATR ledger)" },
  { slug: "sales.return.request", name: "Request sales return (ATR)" },
  { slug: "sales.return.evaluate", name: "Evaluate sales return (CS)" },
  { slug: "sales.return.approve", name: "Approve sales return (TL)" },
  { slug: "sales.return.complete", name: "Complete sales return / restore stock" },
  { slug: "returns.view", name: "View all Returns tabs" },
  { slug: "returns.branch.view", name: "View Branch Returns tab" },
  { slug: "returns.service.view", name: "View Service Returns tab" },
  { slug: "returns.request", name: "Request return" },
  { slug: "returns.evaluate", name: "Evaluate return (CS)" },
  { slug: "returns.approve", name: "Approve return (TL)" },
  { slug: "returns.complete", name: "Complete return / restore stock" },
  { slug: "official_sales.view", name: "View official sales staging" },
  { slug: "official_sales.manage", name: "Manage official sales imports" },
  { slug: "planogram.view", name: "View branch planogram" },
  { slug: "planogram.manage", name: "Manage branch planogram and MIL" },
  { slug: "forecast.view", name: "View forecast and suggested orders" },
  { slug: "forecast.manage", name: "Manage forecast, allocation, and suggested orders" },
  { slug: "announcements.view", name: "View announcements" },
  { slug: "announcements.manage", name: "Manage announcements" },
  { slug: "competitors.view", name: "View competitor observations" },
  { slug: "competitors.manage", name: "Manage competitor observations" },
] as const;

/** Settings-style view grants that pair with *.manage (additive, equivalent until retuned). */
const SETTINGS_VIEW_WITH_MANAGE = [
  "company.view",
  "users.view",
  "departments.view",
  "roles.view",
  "branches.view",
  "dealers.view",
  "service_centers.view",
  "warehouses.view",
  "master_data.view",
  "status_settings.view",
  "ordering_settings.view",
  "aors.view",
  "sap.view",
  "forecast.view",
] as const;

/** Full Service Center ops grants (Excel Phase 2). */
const SERVICE_CENTER_OPS_ALL = [
  "service_centers.view",
  "service_centers.inventory.view",
  "service_centers.sales.view",
  "service_centers.sales.create",
  "service_centers.return.request",
  "service_centers.return.evaluate",
  "service_centers.return.approve",
  "service_centers.return.complete",
  "service_centers.orders.view",
  "service_centers.orders.create",
  "service_centers.orders.approve",
  "service_centers.logistics.view",
  "service_centers.logistics.create",
  "service_centers.logistics.manage",
] as const;

/** Legacy + per-type order view (compat for reports / AE-style read access). */
const ORDERS_VIEW_ALL = [
  "orders.view",
  "orders.manual.view",
  "orders.special.view",
  "orders.auto_replenish.view",
] as const;

/** Legacy + per-type create (PS / tenant admin pattern). */
const ORDERS_CREATE_ALL = [
  "orders.create",
  "orders.manual.create",
  "orders.special.create",
  "orders.auto_replenish.create",
] as const;

/** Legacy + per-type approve (TL / SP / logistics / admin pattern). */
const ORDERS_APPROVE_ALL = [
  "orders.approve",
  "orders.manual.approve",
  "orders.special.approve",
  "orders.auto_replenish.approve",
] as const;

export const ROLES = [
  {
    slug: "super_admin",
    name: "Super Admin",
    description: "Platform operator",
    permissions: PERMISSIONS.map((p) => p.slug),
  },
  {
    slug: "tenant_admin",
    name: "Tenant Admin",
    description: "Tenant administrator",
    permissions: [
      "dashboard.manage",
      ...SETTINGS_VIEW_WITH_MANAGE,
      "company.manage",
      "users.manage",
      "departments.manage",
      "roles.manage",
      "policies.create",
      "policies.approve",
      "audits.create",
      "audits.close",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "branches.manage",
      "dealers.manage",
      "service_centers.manage",
      ...SERVICE_CENTER_OPS_ALL,
      "warehouses.manage",
      "master_data.manage",
      "status_settings.manage",
      "ordering_settings.manage",
      "aors.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_CREATE_ALL,
      ...ORDERS_APPROVE_ALL,
      "logistics.view",
      "logistics.create",
      "logistics.manage",
      "sap.manage",
      "sales.view",
      "sales.create",
      "sales.update",
      "sales.return.view",
      "sales.return.request",
      "sales.return.evaluate",
      "sales.return.approve",
      "sales.return.complete",
      "returns.view",
      "returns.branch.view",
      "returns.service.view",
      "returns.request",
      "returns.evaluate",
      "returns.approve",
      "returns.complete",
      "official_sales.view",
      "official_sales.manage",
      "planogram.manage",
      "forecast.manage",
      "announcements.view",
      "announcements.manage",
      "competitors.view",
      "competitors.manage",
    ],
  },
  {
    slug: "isms_manager",
    name: "ISMS Manager",
    description: "ISMS program manager",
    permissions: [
      "dashboard.manage",
      "users.view",
      "users.manage",
      "departments.view",
      "departments.manage",
      "policies.create",
      "policies.approve",
      "audits.create",
      "audits.close",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "auditor",
    name: "Auditor",
    description: "Internal auditor",
    permissions: [
      "dashboard.manage",
      "audits.create",
      "audits.close",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "policies.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "dept_head",
    name: "Department Head",
    description: "Department head",
    permissions: [
      "dashboard.manage",
      "policies.create",
      "policies.view",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "employee",
    name: "Employee",
    description: "Standard employee",
    permissions: [
      "dashboard.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "policies.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "ps",
    name: "Product Specialist",
    description: "Branch sales — create orders and transfers",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_CREATE_ALL,
      "sales.view",
      "sales.create",
      "sales.return.view",
      "sales.return.request",
      "returns.view",
      "returns.branch.view",
      "returns.service.view",
      "returns.request",
      "service_centers.inventory.view",
      "service_centers.sales.view",
      "service_centers.sales.create",
      "service_centers.return.request",
      "service_centers.orders.view",
      "service_centers.orders.create",
      "planogram.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "tl",
    name: "Team Leader",
    description: "First-level order and transfer approval",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "sales.view",
      "sales.create",
      "sales.return.view",
      "sales.return.request",
      "sales.return.evaluate",
      "sales.return.approve",
      "returns.view",
      "returns.branch.view",
      "returns.service.view",
      "returns.request",
      "returns.evaluate",
      "returns.approve",
      "service_centers.inventory.view",
      "service_centers.sales.view",
      "service_centers.sales.create",
      "service_centers.return.request",
      "service_centers.return.evaluate",
      "service_centers.return.approve",
      "service_centers.orders.view",
      "service_centers.orders.create",
      "service_centers.orders.approve",
      "service_centers.logistics.view",
      "planogram.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "sp",
    name: "Supply Planning",
    description: "Supply Planning — order approval and forecast (xlsx SP)",
    permissions: [
      "dashboard.manage",
      "master_data.view",
      "master_data.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "planogram.manage",
      "forecast.view",
      "forecast.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "spa",
    name: "Supply Planning Associate",
    description: "SPA — same approval scope as SP for processed-order reporting",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "planogram.view",
      "forecast.view",
      "forecast.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "supply_planning",
    name: "Supply Planning (role alias)",
    description: "Alias for SP permissions",
    permissions: [
      "dashboard.manage",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "forecast.view",
      "forecast.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "supply_planning_associate",
    name: "Supply Planning Associate (role alias)",
    description: "Alias for SPA permissions",
    permissions: [
      "dashboard.manage",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "forecast.view",
      "forecast.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "logistics",
    name: "Logistics",
    description: "Delivery, transfer, pull-out processing",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      ...ORDERS_APPROVE_ALL,
      "logistics.view",
      "logistics.create",
      "logistics.manage",
      "sap.view",
      "sap.manage",
      "sales.view",
      "sales.return.view",
      "sales.return.complete",
      "returns.view",
      "returns.branch.view",
      "returns.service.view",
      "returns.complete",
      "service_centers.inventory.view",
      "service_centers.return.complete",
      "service_centers.logistics.view",
      "service_centers.logistics.create",
      "service_centers.logistics.manage",
      "service_centers.orders.view",
      "service_centers.orders.approve",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "ae",
    name: "Area Executive",
    description: "Multi-branch dashboard visibility",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      ...ORDERS_VIEW_ALL,
      "reports.view",
      "official_sales.view",
      "official_sales.manage",
      "audit_logs.view",
      "serial_logs.view",
      "planogram.view",
      "service_centers.view",
      "service_centers.inventory.view",
      "service_centers.sales.view",
      "service_centers.orders.view",
      "service_centers.logistics.view",
      "announcements.view",
      "competitors.view",
    ],
  },
  {
    slug: "accounting",
    name: "Accounting",
    description: "Official Sales processing and sale header corrections",
    permissions: [
      "dashboard.manage",
      "inventory.view",
      "sales.view",
      "sales.update",
      "sales.return.view",
      "returns.view",
      "returns.branch.view",
      "official_sales.view",
      "official_sales.manage",
      "reports.view",
      "audit_logs.view",
      "serial_logs.view",
      "announcements.view",
      "competitors.view",
    ],
  },
] as const;

export const DEPARTMENTS = ["Compliance", "Engineering", "Human Resources", "Operations"] as const;

export const USER_DEPARTMENTS: Record<string, (typeof DEPARTMENTS)[number]> = {
  "employee@demo.local": "Engineering",
  "depthead@demo.local": "Operations",
  "isms@demo.local": "Compliance",
  "auditor@demo.local": "Compliance",
  "admin@demo.local": "Human Resources",
  "ps@demo.local": "Operations",
  "tl@demo.local": "Operations",
  "sp@demo.local": "Operations",
  "spa@demo.local": "Operations",
  "logistics@demo.local": "Operations",
  "ae@demo.local": "Operations",
  "accounting@demo.local": "Operations",
};

export type SeedProfile =
  | "minimal"
  | "full"
  | "core"
  | "status"
  | "brs"
  | "schedules"
  | "branches"
  | "psg"
  | "warehouse";

export function resolveSeedProfile(): SeedProfile {
  const raw = process.env.SEED_PROFILE?.trim().toLowerCase();
  if (
    raw === "full" ||
    raw === "core" ||
    raw === "status" ||
    raw === "brs" ||
    raw === "schedules" ||
    raw === "branches" ||
    raw === "psg" ||
    raw === "warehouse" ||
    raw === "minimal"
  ) {
    return raw;
  }
  return "minimal";
}
