import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    lineHeight: 1.4,
  },
  title: {
    fontSize: 16,
    fontFamily: "Helvetica-Bold",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 11,
    color: "#444",
    marginBottom: 16,
  },
  section: {
    marginBottom: 12,
  },
  sectionLabel: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    textTransform: "uppercase",
    color: "#666",
    marginBottom: 6,
  },
  row: {
    flexDirection: "row",
    marginBottom: 3,
  },
  label: {
    width: "38%",
    color: "#555",
  },
  value: {
    width: "62%",
    fontFamily: "Helvetica",
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    paddingBottom: 4,
    marginBottom: 4,
    fontFamily: "Helvetica-Bold",
  },
  tableRow: {
    flexDirection: "row",
    marginBottom: 2,
  },
  colModel: { width: "40%" },
  colSn: { width: "35%" },
  colAmount: { width: "25%", textAlign: "right" },
  footer: {
    position: "absolute",
    bottom: 28,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#888",
    textAlign: "center",
  },
});

export type AtrOdrfPdfLine = {
  modelLabel: string;
  serialNo: string;
  saleAmount: string;
};

export type AtrOdrfPdfData = {
  documentTitle: string;
  actionTypeLabel: string;
  transactionNo: string;
  transactionDate: string | null;
  branchName: string;
  customerName: string | null;
  documentTypeName: string | null;
  stockStatusCode: string;
  problemDescriptionText: string | null;
  requestedByName: string;
  requestedAt: string;
  serviceCenterName?: string | null;
  classification?: string | null;
  serviceModelLabel?: string | null;
  customerDealerBranch?: string | null;
  natureOfTransaction?: string | null;
  refContactPo?: string | null;
  warehouseLocationLabel?: string | null;
  lines: AtrOdrfPdfLine[];
};

function MetaRow({ label, value }: { label: string; value: string | null | undefined }) {
  const display = value?.trim() || "—";
  return (
    <View style={styles.row}>
      <Text style={styles.label}>{label}</Text>
      <Text style={styles.value}>{display}</Text>
    </View>
  );
}

export function AtrOdrfPdfDocument(props: AtrOdrfPdfData) {
  const showService =
    Boolean(props.serviceCenterName) ||
    Boolean(props.classification) ||
    Boolean(props.serviceModelLabel) ||
    Boolean(props.customerDealerBranch) ||
    Boolean(props.natureOfTransaction) ||
    Boolean(props.refContactPo) ||
    Boolean(props.warehouseLocationLabel);

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{props.documentTitle}</Text>
        <Text style={styles.subtitle}>
          {props.actionTypeLabel} · Generated by FINDEN ISMS
        </Text>

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Sale / return</Text>
          <MetaRow label="Transaction no." value={props.transactionNo} />
          <MetaRow label="Transaction date" value={props.transactionDate} />
          <MetaRow label="Branch sold" value={props.branchName} />
          <MetaRow label="Customer" value={props.customerName} />
          <MetaRow label="Document type" value={props.documentTypeName} />
          <MetaRow label="Stock status" value={props.stockStatusCode} />
          <MetaRow label="Problem description" value={props.problemDescriptionText} />
          <MetaRow label="Requested by" value={props.requestedByName} />
          <MetaRow label="Requested at" value={props.requestedAt} />
        </View>

        {showService ? (
          <View style={styles.section}>
            <Text style={styles.sectionLabel}>Service return</Text>
            <MetaRow label="Service center" value={props.serviceCenterName} />
            <MetaRow label="Classification" value={props.classification} />
            <MetaRow label="Model" value={props.serviceModelLabel} />
            <MetaRow
              label="Customer / dealer branch"
              value={props.customerDealerBranch}
            />
            <MetaRow label="Nature of transaction" value={props.natureOfTransaction} />
            <MetaRow label="Ref. contact / P.O." value={props.refContactPo} />
            <MetaRow label="Warehouse location" value={props.warehouseLocationLabel} />
          </View>
        ) : null}

        <View style={styles.section}>
          <Text style={styles.sectionLabel}>Units</Text>
          <View style={styles.tableHeader}>
            <Text style={styles.colModel}>Model</Text>
            <Text style={styles.colSn}>Serial</Text>
            <Text style={styles.colAmount}>Amount</Text>
          </View>
          {props.lines.length === 0 ? (
            <Text>—</Text>
          ) : (
            props.lines.map((line, index) => (
              <View key={`${line.serialNo}-${index}`} style={styles.tableRow}>
                <Text style={styles.colModel}>{line.modelLabel || "—"}</Text>
                <Text style={styles.colSn}>{line.serialNo || "—"}</Text>
                <Text style={styles.colAmount}>{line.saleAmount || "—"}</Text>
              </View>
            ))
          )}
        </View>

        <Text style={styles.footer}>ATR / ODRF · {props.transactionNo}</Text>
      </Page>
    </Document>
  );
}
