export const BRS_PERMISSIONS = [
  { slug: "branches.manage", name: "Manage branches" },
  { slug: "dealers.manage", name: "Manage dealers" },
  { slug: "service_centers.manage", name: "Manage service centers" },
  { slug: "warehouses.manage", name: "Manage warehouses" },
  { slug: "master_data.manage", name: "Manage master data" },
  { slug: "aors.manage", name: "Manage areas of responsibility" },
  { slug: "inventory.view", name: "View inventory" },
  { slug: "inventory.manage", name: "Manage inventory status" },
  { slug: "orders.create", name: "Create branch orders" },
  { slug: "orders.approve", name: "Approve branch orders" },
  { slug: "orders.view", name: "View branch orders" },
  { slug: "orders.manual.view", name: "View manual orders" },
  { slug: "orders.manual.create", name: "Create manual orders" },
  { slug: "orders.manual.approve", name: "Approve manual orders" },
  { slug: "orders.special.view", name: "View special orders" },
  { slug: "orders.special.create", name: "Create special orders" },
  { slug: "orders.special.approve", name: "Approve special orders" },
  { slug: "orders.auto_replenish.view", name: "View auto-replenish orders" },
  { slug: "orders.auto_replenish.create", name: "Create auto-replenish orders" },
  { slug: "orders.auto_replenish.approve", name: "Approve auto-replenish orders" },
  { slug: "logistics.view", name: "View logistics" },
  { slug: "logistics.create", name: "Create logistics transactions" },
  { slug: "logistics.manage", name: "Manage logistics transactions" },
  { slug: "sap.view", name: "View SAP integration" },
  { slug: "sap.manage", name: "Manage SAP integration" },
  { slug: "sales.view", name: "View sales and ATR" },
  { slug: "sales.create", name: "Record branch sales" },
  { slug: "sales.return.request", name: "Request sales return (ATR)" },
  { slug: "sales.return.evaluate", name: "Evaluate sales return (CS)" },
  { slug: "sales.return.approve", name: "Approve sales return (TL)" },
  { slug: "sales.return.complete", name: "Complete sales return / restore stock" },
] as const;
