export const BRS_PERMISSIONS = [
  { slug: "branches.manage", name: "Manage branches" },
  { slug: "dealers.manage", name: "Manage dealers" },
  { slug: "service_centers.manage", name: "Manage service centers" },
  { slug: "service_centers.view", name: "View service centers" },
  { slug: "service_centers.inventory.view", name: "View service center inventory" },
  { slug: "service_centers.sales.view", name: "View service center sales" },
  { slug: "service_centers.sales.create", name: "Create service center sales" },
  { slug: "service_centers.return.request", name: "Request service center return (ATR)" },
  { slug: "service_centers.return.evaluate", name: "Evaluate service center return (CS)" },
  { slug: "service_centers.return.approve", name: "Approve service center return (TL)" },
  { slug: "service_centers.return.complete", name: "Complete service center return / restore stock" },
  { slug: "service_centers.orders.view", name: "View service center orders" },
  { slug: "service_centers.orders.create", name: "Create service center orders" },
  { slug: "service_centers.orders.approve", name: "Approve service center orders" },
  { slug: "service_centers.logistics.view", name: "View service center logistics" },
  { slug: "service_centers.logistics.create", name: "Create service center logistics" },
  { slug: "service_centers.logistics.manage", name: "Manage service center logistics" },
  { slug: "warehouses.manage", name: "Manage warehouses" },
  { slug: "master_data.manage", name: "Manage master data" },
  { slug: "aors.manage", name: "Manage areas of responsibility" },
  { slug: "inventory.view", name: "View inventory" },
  { slug: "inventory.manage", name: "Manage inventory status" },
  { slug: "orders.create", name: "Create branch orders" },
  { slug: "orders.approve", name: "Approve branch orders" },
  { slug: "orders.view", name: "View branch orders" },
  { slug: "orders.manual.view", name: "View manual orders" },
  { slug: "orders.manual.create", name: "Create manual orders" },
  { slug: "orders.manual.approve", name: "Approve manual orders" },
  { slug: "orders.special.view", name: "View special orders" },
  { slug: "orders.special.create", name: "Create special orders" },
  { slug: "orders.special.approve", name: "Approve special orders" },
  { slug: "orders.auto_replenish.view", name: "View auto-replenish orders" },
  { slug: "orders.auto_replenish.create", name: "Create auto-replenish orders" },
  { slug: "orders.auto_replenish.approve", name: "Approve auto-replenish orders" },
  { slug: "logistics.view", name: "View logistics" },
  { slug: "logistics.create", name: "Create logistics transactions" },
  { slug: "logistics.manage", name: "Manage logistics transactions" },
  { slug: "sap.view", name: "View SAP integration" },
  { slug: "sap.manage", name: "Manage SAP integration" },
  { slug: "sales.view", name: "View sales and ATR" },
  { slug: "sales.create", name: "Record branch sales" },
  { slug: "sales.update", name: "Edit sales transaction headers" },
  { slug: "sales.return.view", name: "View sales returns (ATR ledger)" },
  { slug: "sales.return.request", name: "Request sales return (ATR)" },
  { slug: "sales.return.evaluate", name: "Evaluate sales return (CS)" },
  { slug: "sales.return.approve", name: "Approve sales return (TL)" },
  { slug: "sales.return.complete", name: "Complete sales return / restore stock" },
  { slug: "returns.view", name: "View returns / replacement" },
  { slug: "returns.request", name: "Request return" },
  { slug: "returns.evaluate", name: "Evaluate return (CS)" },
  { slug: "returns.approve", name: "Approve return (TL)" },
  { slug: "returns.complete", name: "Complete return / restore stock" },
] as const;
