/**
 * Philippine REGION → PROVINCE master list for seed / lookup bootstrap.
 * Labels are seeded exactly as provided (including NCR cities and ONLINE).
 */
export const PH_REGION_PROVINCES: ReadonlyArray<{ region: string; province: string }> = [
  { region: "R7: C. VISAYAS", province: "BOHOL" },
  { region: "R12: SOCSKSARGEN", province: "SOUTH COTABATO" },
  { region: "R5: BICOL", province: "ALBAY" },
  { region: "R11: DAVAO", province: "DAVAO DEL SUR" },
  { region: "R11: DAVAO", province: "DAVAO" },
  { region: "NCR", province: "QUEZON CITY" },
  { region: "R7: C. VISAYAS", province: "CEBU" },
  { region: "R4-A: CALABARZON", province: "LAGUNA" },
  { region: "R4-A: CALABARZON", province: "RIZAL" },
  { region: "R10: N. MINDANAO", province: "MISAMIS ORIENTAL" },
  { region: "NCR", province: "MUNTINLUPA" },
  { region: "NCR", province: "MAKATI" },
  { region: "NCR", province: "MANILA" },
  { region: "R2: CAGAYAN VALLEY", province: "ISABELA" },
  { region: "NCR", province: "PARANAQUE" },
  { region: "NCR", province: "LAS PINAS" },
  { region: "R4-A: CALABARZON", province: "BATANGAS" },
  { region: "R4-A: CALABARZON", province: "QUEZON" },
  { region: "R4-A: CALABARZON", province: "CAVITE" },
  { region: "NCR", province: "PASIG" },
  { region: "R3: C. LUZON", province: "BULACAN" },
  { region: "R3: C. LUZON", province: "TARLAC" },
  { region: "R2: CAGAYAN VALLEY", province: "CAGAYAN" },
  { region: "R3: C. LUZON", province: "NUEVA ECIJA" },
  { region: "R3: C. LUZON", province: "PAMPANGA" },
  { region: "R1: ILOCOS", province: "ILOCOS NORTE" },
  { region: "R4-B: MIMAROPA", province: "ORIENTAL MINDORO" },
  { region: "NCR", province: "TAGUIG" },
  { region: "NCR", province: "CALOOCAN" },
  { region: "NCR", province: "MARIKINA" },
  { region: "NCR", province: "PASAY" },
  { region: "ONLINE", province: "ONLINE" },
  { region: "R1: ILOCOS", province: "LA UNION" },
  { region: "R1: ILOCOS", province: "PANGASINAN" },
  { region: "R2: CAGAYAN VALLEY", province: "NUEVA VIZCAYA" },
  { region: "CAR", province: "BENGUET" },
  { region: "NCR", province: "MANDALUYONG" },
  { region: "NCR", province: "SAN JUAN" },
  { region: "R4-B: MIMAROPA", province: "PALAWAN" },
  { region: "R3: C. LUZON", province: "ZAMBALES" },
  { region: "R9: ZAMBOANGA", province: "ZAMBOANGA DEL NORTE" },
  { region: "R6: W. VISAYAS", province: "ANTIQUE" },
  { region: "R7: C. VISAYAS", province: "NEGROS ORIENTAL" },
  { region: "R6: W. VISAYAS", province: "NEGROS OCCIDENTAL" },
  { region: "R6: W. VISAYAS", province: "AKLAN" },
  { region: "R8: E. VISAYAS", province: "LEYTE" },
  { region: "R6: W. VISAYAS", province: "CAPIZ" },
  { region: "R10: N. MINDANAO", province: "BUKIDNON" },
  { region: "R6: W. VISAYAS", province: "ILOILO" },
  { region: "R10: N. MINDANAO", province: "CAMIGUIN" },
  { region: "R8: E. VISAYAS", province: "NORTHERN SAMAR" },
  { region: "R8: E. VISAYAS", province: "SOUTHERN LEYTE" },
  { region: "R8: E. VISAYAS", province: "SAMAR" },
  { region: "R13: CARAGA", province: "AGUSAN DEL NORTE" },
  { region: "R8: E. VISAYAS", province: "BILIRAN" },
  { region: "R9: ZAMBOANGA", province: "ZAMBOANGA DEL SUR" },
  { region: "R11: DAVAO", province: "DAVAO DEL NORTE" },
  { region: "R12: SOCSKSARGEN", province: "SARANGANI" },
  { region: "R11: DAVAO", province: "DAVAO ORIENTAL" },
  { region: "R10: N. MINDANAO", province: "LANAO DEL NORTE" },
  { region: "R10: N. MINDANAO", province: "MISAMIS OCCIDENTAL" },
  { region: "R12: SOCSKSARGEN", province: "NORTH COTABATO" },
  { region: "R12: SOCSKSARGEN", province: "SULTAN KUDARAT" },
  { region: "R5: BICOL", province: "CAMARINES SUR" },
  { region: "R1: ILOCOS", province: "ILOCOS SUR" },
  { region: "R13: CARAGA", province: "AGUSAN DEL SUR" },
  { region: "R3: C. LUZON", province: "BATAAN" },
  { region: "NCR", province: "MALABON CITY" },
  { region: "NCR", province: "VALENZUELA" },
  { region: "R2: CAGAYAN VALLEY", province: "APAYAO" },
  { region: "R13: CARAGA", province: "SURIGAO DEL NORTE" },
  { region: "R5: BICOL", province: "SORSOGON" },
  { region: "R5: BICOL", province: "CAMARINES NORTE" },
  { region: "R5: BICOL", province: "MASBATE" },
  { region: "R3: C. LUZON", province: "AURORA" },
  { region: "ARMM", province: "MAGUINDANAO" },
  { region: "R9: ZAMBOANGA", province: "ZAMBOANGA SIBUGAY" },
  { region: "R8: E. VISAYAS", province: "EASTERN SAMAR" },
  { region: "R10: N. MINDANAO", province: "CAGAYAN DE ORO" },
  { region: "R13: CARAGA", province: "TANDAG" },
  { region: "R13: CARAGA", province: "SURIGAO DEL SUR" },
  { region: "CAR", province: "ABRA" },
];

export function uniquePhRegionNames(): string[] {
  return [...new Set(PH_REGION_PROVINCES.map((row) => row.region))];
}
